export const primary_color = "#599EED";
export const primary_color_light = "#599EED";
export const bg_color = "#fff";
// export const bg_color = "#f7f7f7";
export const white = "#fff";
export const black = "#000";
export const green = "#2E7D32";
export const red = "#D50000";
export const gray = "#eee";
